version: '3.9'
services:

  app:
    build: ./php 
    container_name: walkin-app
    volumes:
      - ./walkin:/var/www/html   # Single volume named 'app'  
      - ./vendor:/usr/local/bin/vendor  # composer
      - ./php/php.ini:/usr/local/etc/php/php.ini  # แชร์ไฟล์ php.ini
    ports:
      - '8888:80'        
    stdin_open: true
    tty: true
    restart: always
    environment:
      TZ: Asia/Bangkok        
    networks:
      - web_network   

networks:
  web_network:
    name: mysql_default
    external: true
