services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: esdpsd
      MARIADB_DATABASE: esdpsd
      MARIADB_PASSWORD: m74WzpNE
    networks:
      - web_network      

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: db_phpmyadmin    
    ports:
      - '8080:80'
    restart: unless-stopped 
    environment:
      PMA_HOST: db
      TZ: Asia/Bangkok  
    networks:
      - web_network 

networks:
  web_network:
    name: mysql_default
    driver: bridge 